add support for voltage meter
bwesterb/dsmrp1 pull request #2
Opened 2017-05-11 18:57 UTC by githubcdr

My meter has a voltage OBIS, I added this

2017-05-11 19:05 UTC, bwesterb requested changes
Thanks!  I have one question: why not use `_unit`?

2017-05-11 19:05 UTC, bwesterb commented on src/dsmrp1.py
> +_voltage = lambda x: x.split('*')[0]
Why not use `_unit`?

2017-05-11 19:08 UTC, githubcdr commented on src/dsmrp1.py
> +_voltage = lambda x: x.split('*')[0]
I don't know, I'm not a experienced python programmer, I wanted just the raw value not "(223.6*V)", feel free to improve!

2017-05-11 22:18 UTC, bwesterb commented on src/dsmrp1.py
> +_voltage = lambda x: x.split('*')[0]
Ok, I'll write a patch tomorrow!

2017-05-13 10:17 UTC, bwesterb commented
Added to commit d87afbef684d32487c494698873bd691e5f11b9e

Dit it work?

2017-05-13 11:02 UTC, closed without merging